import { vi } from 'vitest'
import type { CanvasItem } from '@/api/endpoints/projects'
import type { CanvasWorkspaceItemLayerProps } from '@/pages/dashboard/CanvasPage/components/canvasRenderContracts'
import { normalizeReferenceImages } from '@/pages/dashboard/CanvasPage/generatorCapabilities'
import { canvasViewportFixture } from './canvasViewportFixture'
import { createTranslationFixture } from './translationFixture'

export function canvasRenderFixture(item: CanvasItem, selectedItems: string[] = []): CanvasWorkspaceItemLayerProps {
return {
canvasItems: [item],
clampCanvasStackZIndex: (value?: number) => value ?? 0,
isHoverOnlyFailedVideoTask: () => false,
getItemDims: (currentItem: CanvasItem) => ({ width: currentItem.width || 1, height: currentItem.height || 1 }),
activeDropdown: null,
hoveredMarkableImageId: null,
isTransientMarkModeActive: () => false,
activeTool: "select",
markModifierState: { altKey: false, metaKey: false, ctrlKey: false },
cropState: null,
selectedItems: selectedItems,
getMediaSelectionOverlayMetrics: () => ({ handleSize: 12, handleOffset: 6, borderWidth: 5 }),
zoom: 100,
offset: { x: 0, y: 0 },
canvasRef: canvasViewportFixture(),
selectedSingleItemRect: null,
getResolvedImageCapability: () => null,
getResolvedVideoCapability: () => null,
getResolvedVideoDurations: () => [],
availableImageModels: [],
availableVideoModels: [],
imageModel: "",
imageProvider: "",
videoModel: "",
videoProvider: "",
getItemReferenceImages: () => [],
shouldDisableVideoAspectRatio: () => false,
getVideoGeneratorCapability: () => ({ supportsReferenceImages: false, maxReferenceImages: 0, supportsFirstFrame: false, supportsTailFrame: false, disableAspectRatioWhenImages: false, imageModesConflict: false }),
getCanvasSelectionBorder: (width: number) => `${width}px solid rgb(59, 130, 246)`,
textEditingItemId: null,
handleStartTextEdit: vi.fn(),
handleCommitTextEdit: vi.fn(),
handleCancelTextEdit: vi.fn(),
handleItemMouseDown: vi.fn(),
setSelectedItems: vi.fn(),
setContextMenu: vi.fn(),
setActiveContextMenuItem: vi.fn(),
beginTransaction: vi.fn(),
setActiveGuides: vi.fn(),
movingItemIdsRef: { current: new Set() },
setMediaResizeState: vi.fn(),
resizingHandle: { current: null },
dragItemStart: { current: null },
resizingStart: { current: null },
getCanvasSelectionHandleAppearance: vi.fn(() => ({
          border: '2px solid rgb(59, 130, 246)',
          backgroundColor: '#fff',
        })),
isDark: false,
setBrushResizeState: vi.fn(),
setHoveredMarkableImageId: vi.fn(),
getCanvasSelectionContainerOverflow: () => 'hidden',
MARK_CURSOR: "crosshair",
imageAnchoredVideoDraft: null,
imageDetailItemId: null,
isMarkModifierPressed: () => false,
addMark: vi.fn(),
handleAppendImageMentionToChat: vi.fn(),
updateItem: vi.fn(),
getMediaDisplayInitializationUpdate: () => null,
getTextRedrawExtractingBadgeStyle: vi.fn(() => ({})),
t: createTranslationFixture(),
cropDragState: null,
handleCropMoveMouseDown: vi.fn(),
handleCropHandleMouseDown: vi.fn(),
renderSelectionHandles: vi.fn(),
shouldShowGeneratorControlPanel: () => false,
setActiveDropdown: vi.fn(),
referenceImageInputRef: { current: null },
openGeneratorAssetLibrary: vi.fn(),
openGeneratorReferenceGallery: vi.fn(),
firstFrameImageInputRef: { current: null },
tailFrameImageInputRef: { current: null },
handleGenerateImage: vi.fn(),
handleGenerateVideo: vi.fn(),
getItemAmountCents: () => null,
formatResolutionOptionLabel: (value: string) => value,
standardSuffix: "standard",
imageRes: "1K",
videoQuality: "720p",
videoDuration: "5",
normalizeReferenceImages,
withReferenceImages: (reference_images) => ({ reference_images }),
getImageGeneratorCapability: () => ({ supportsReferenceImages: false, maxReferenceImages: 0 }),
imageRatio: "1:1",
videoAspect: "16:9",
ratioHintLabels: { square: 'square', landscape: 'landscape', portrait: 'portrait' },
formatAspectRatioOptionLabelWithDimensions: (value: string) => value,
cropCommitMode: "freeform",
handleCropDimensionChange: vi.fn(),
CROP_PRESET_GROUPS: [],
setCropExpandedGroups: vi.fn(),
cropExpandedGroups: {},
handleSelectCropPreset: vi.fn(),
setCropState: vi.fn(),
handleApplyCrop: vi.fn(),
imageAnchoredImageDraft: null,
imageAnchoredImageDraftItem: null,
anchoredImageReferenceInputRef: { current: null },
updateImageAnchoredImageDraft: vi.fn(),
setPreviewImageUrl: vi.fn(),
handleGenerateAnchoredImage: vi.fn(),
imageAnchoredVideoDraftItem: null,
imageAnchoredVideoCapability: null,
imageAnchoredVideoAllowedDurations: [],
anchoredReferenceImageInputRef: { current: null },
anchoredFirstFrameImageInputRef: { current: null },
anchoredTailFrameImageInputRef: { current: null },
updateImageAnchoredVideoDraft: vi.fn(),
handleMoveAnchoredVideoSourcePlacement: vi.fn(),
handleGenerateAnchoredVideo: vi.fn(),
marks: [],
textRedrawExtractingItemIds: new Set<string>(),
isSceneReady: false
}
}
