# syntax=docker/dockerfile:1.7-labs
FROM node:22-alpine AS base

WORKDIR /app

COPY frontend/package*.json ./

RUN --mount=type=cache,target=/root/.npm \
    npm ci --frozen-lockfile --registry=https://registry.npmmirror.com && \
    mkdir -p /opt/xscz/metadata && \
    sha256sum package-lock.json | awk '{print $1}' > /opt/xscz/metadata/frontend-package-lock.sha256 && \
    cp /opt/xscz/metadata/frontend-package-lock.sha256 /app/node_modules/.package-lock.sha256
