from __future__ import annotations

RUN_STATUS_QUEUED = "queued"
RUN_STATUS_RUNNING = "running"
RUN_STATUS_WAITING_INPUT = "waiting_input"
RUN_STATUS_COMPLETED = "completed"
RUN_STATUS_FAILED = "failed"
RUN_STATUS_CANCELLED = "cancelled"

RUN_ACTIVE_STATUSES = {
    RUN_STATUS_QUEUED,
    RUN_STATUS_RUNNING,
    RUN_STATUS_WAITING_INPUT,
}
RUN_TERMINAL_STATUSES = {
    RUN_STATUS_COMPLETED,
    RUN_STATUS_FAILED,
    RUN_STATUS_CANCELLED,
}

STEP_STATUS_QUEUED = "queued"
STEP_STATUS_CLAIMED = "claimed"
STEP_STATUS_RUNNING = "running"
STEP_STATUS_WAITING_INPUT = "waiting_input"
STEP_STATUS_SUCCEEDED = "succeeded"
STEP_STATUS_FAILED = "failed"
STEP_STATUS_CANCELLED = "cancelled"

STEP_CLAIMABLE_STATUSES = {
    STEP_STATUS_QUEUED,
    STEP_STATUS_CLAIMED,
    STEP_STATUS_RUNNING,
}
STEP_TERMINAL_STATUSES = {
    STEP_STATUS_SUCCEEDED,
    STEP_STATUS_FAILED,
    STEP_STATUS_CANCELLED,
    STEP_STATUS_WAITING_INPUT,
}

RUN_KIND_MESSAGE = "message"
RUN_KIND_RESUME_INTERACTION = "resume_interaction"
RUN_KIND_START_PLAN = "start_plan"
RUN_KIND_REVISE_PLAN = "revise_plan"

RUN_KINDS = {
    RUN_KIND_MESSAGE,
    RUN_KIND_RESUME_INTERACTION,
    RUN_KIND_START_PLAN,
    RUN_KIND_REVISE_PLAN,
}

STEP_PREPARE_SKILL = "prepare_skill"
STEP_DISCOVERY_SCHEMA = "discovery_schema"
STEP_WAIT_USER_INPUT = "wait_user_input"
STEP_APPLY_USER_INPUT = "apply_user_input"
STEP_PREPARE_CONTEXT_SESSION = "prepare_context_session"
STEP_RENDER_CONTEXT = "render_context"
STEP_MODEL_TURN = "model_turn"
STEP_EXECUTE_TOOL = "execute_tool"
STEP_PERSIST_TOOL_RESULT = "persist_tool_result"
STEP_PLAN_LIFECYCLE = "plan_lifecycle"
STEP_FINALIZE = "finalize"
STEP_FAIL_OR_CANCEL = "fail_or_cancel"

NATIVE_STEP_TYPES = {
    STEP_PREPARE_SKILL,
    STEP_DISCOVERY_SCHEMA,
    STEP_WAIT_USER_INPUT,
    STEP_APPLY_USER_INPUT,
    STEP_PREPARE_CONTEXT_SESSION,
    STEP_RENDER_CONTEXT,
    STEP_MODEL_TURN,
    STEP_EXECUTE_TOOL,
    STEP_PERSIST_TOOL_RESULT,
    STEP_PLAN_LIFECYCLE,
    STEP_FINALIZE,
    STEP_FAIL_OR_CANCEL,
}
