from app.core.config import (
    DB_POOL_PRE_PING,
    DB_POOL_RECYCLE,
    DB_POOL_TIMEOUT,
    DB_POOL_USE_LIFO,
    HARNESS_ACTIVE_RUN_STATE_CACHE_MAX_ENTRIES,
    HARNESS_ACTIVE_RUN_STATE_CACHE_TTL_SECONDS,
    HARNESS_ANALYZE_IMAGE_STREAM_DELTA_FLUSH_CHARS,
    HARNESS_ANALYZE_IMAGE_STREAM_DELTA_FLUSH_INTERVAL_SECONDS,
    HARNESS_PRESENTATION_DELTA_PERSIST_FLUSH_INTERVAL_SECONDS,
    HARNESS_PRESENTATION_DELTA_PERSIST_MAX_BATCH_SIZE,
    HARNESS_PRESENTATION_DELTA_PERSIST_MAX_MERGED_CHARS,
    HARNESS_PRESENTATION_DELTA_PERSIST_QUEUE_MAX_SIZE,
    Settings,
)


def test_runtime_sizing_defaults_fit_the_recommended_single_host_profile(monkeypatch):
    for key in (
        "WEB_CONCURRENCY",
        "DB_POOL_SIZE",
        "DB_MAX_OVERFLOW",
    ):
        monkeypatch.delenv(key, raising=False)

    settings = Settings(_env_file=None)

    assert settings.WEB_CONCURRENCY == 6
    assert settings.DB_POOL_SIZE == 10
    assert settings.DB_MAX_OVERFLOW == 10
    assert settings.HARNESS_PRESENTATION_DELTA_ASYNC_PERSIST_ENABLED is True
    assert HARNESS_ANALYZE_IMAGE_STREAM_DELTA_FLUSH_INTERVAL_SECONDS == 1.0
    assert HARNESS_ANALYZE_IMAGE_STREAM_DELTA_FLUSH_CHARS == 512
    assert HARNESS_PRESENTATION_DELTA_PERSIST_FLUSH_INTERVAL_SECONDS == 1.0
    assert HARNESS_PRESENTATION_DELTA_PERSIST_MAX_BATCH_SIZE == 200
    assert HARNESS_PRESENTATION_DELTA_PERSIST_QUEUE_MAX_SIZE == 5000
    assert HARNESS_PRESENTATION_DELTA_PERSIST_MAX_MERGED_CHARS == 8192
    assert HARNESS_ACTIVE_RUN_STATE_CACHE_TTL_SECONDS == 2.0
    assert HARNESS_ACTIVE_RUN_STATE_CACHE_MAX_ENTRIES == 10000
    assert DB_POOL_TIMEOUT == 30
    assert DB_POOL_RECYCLE == 1800
    assert DB_POOL_PRE_PING is True
    assert DB_POOL_USE_LIFO is True
